name: smart_ride_ug
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.3.0 # Navigation
  flutter_animate: ^4.5.0 # Premium animations
  flutter_map: ^8.3.1 # Map functionality (OpenStreetMap)
  latlong2: ^0.10.1
  flutter_bloc: ^9.1.1 # State management (ADR-002)
  equatable: 2.1.0 # Value equality for BLoC events/states
  # ... existing dependencies ...
  firebase_messaging: ^15.1.0 # Push notifications
  flutter_local_notifications: ^18.0.0 # Local notifications
  shared_preferences: ^2.5.0 # Persistent storage for user preferences, so that the app works offline and remembers the user when they reopen the app
  # --- FIREBASE DEPENDENCIES ---
  firebase_core: ^3.3.0 # Firebase Core
  firebase_auth: ^5.3.0 # Authentication
  cloud_firestore: ^5.4.0 # Firestore Database

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/bus_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/bus_logo.png"
